import { readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import withSerwistInit from '@serwist/next';

const isProd = process.env.NODE_ENV === 'production';

// GitHub Pages serves the app from https://<account>.github.io/pocket-session-planner/,
// so every emitted URL needs the repository name in front of it. Overridable so a
// user-page or custom-domain deploy can set an empty base path.
const basePath = isProd ? (process.env.NEXT_PUBLIC_BASE_PATH ?? '/pocket-session-planner') : '';

const APP_DIR = fileURLToPath(new URL('./src/app', import.meta.url));

/**
 * Every route in the app, read off the App Router tree.
 *
 * These have to reach the precache manifest somehow. `@serwist/next` builds it during the
 * **webpack** phase, which finishes before `output: 'export'` has written a single HTML
 * file — so without this the manifest contains chunks and icons but not one page, and a cold
 * offline load of `/run/` finds nothing.
 *
 * It was a hand-written list until `/plan/challenges/` shipped without being added to it:
 * the route built, deployed, and worked on every online device, and only a cold offline tap
 * from the phase editor would have caught it. A list that must be edited in step with the
 * filesystem eventually will not be, so the filesystem is now the list.
 *
 * `trailingSlash: true` means each route resolves to `<route>/index.html`, so that is what
 * gets precached.
 */
function findRoutes(dir = APP_DIR, segments = []) {
  const entries = readdirSync(dir, { withFileTypes: true });
  const routes = entries.some((entry) => entry.isFile() && entry.name === 'page.tsx')
    ? [`/${segments.map((segment) => `${segment}/`).join('')}`]
    : [];

  for (const entry of entries.filter((candidate) => candidate.isDirectory())) {
    // The mapping below assumes a directory name *is* its URL segment. A dynamic segment
    // cannot be statically exported without `generateStaticParams` (ADR 0003 rules them
    // out), and a route group is spelled in the tree but not in the URL — so both would
    // silently precache a path that does not exist. Fail the build instead.
    if (/^[[(]/.test(entry.name)) {
      throw new Error(
        `next.config.mjs cannot derive a URL for the App Router directory "${entry.name}". ` +
          'Dynamic segments are ruled out by ADR 0003; route groups need this scan taught ' +
          'to skip them before one ships.',
      );
    }
    routes.push(...findRoutes(`${dir}/${entry.name}`, [...segments, entry.name]));
  }

  return routes;
}

const ROUTES = findRoutes();

// The scan is the kind of thing that fails quietly — a moved directory or a renamed page
// file yields an empty list, and an app that precaches no pages still builds, installs, and
// then shows nothing at all on the first offline open.
if (!ROUTES.includes('/')) {
  throw new Error(`next.config.mjs found no home route under ${APP_DIR}; the route scan is wrong.`);
}

/**
 * Icons and screenshots, listed explicitly rather than left to the plugin's `public/` scan.
 *
 * The scan is both platform-sensitive (it emitted Windows separators) and quiet about
 * failure — a manifest that silently loses its icons still builds, installs, and then shows
 * a blank tile on someone's home screen. Naming them here makes their absence a build-time
 * mistake instead of a field-time one.
 */
const PUBLIC_ASSETS = [
  '/icons/icon-192.png',
  '/icons/icon-512.png',
  '/icons/icon-maskable-512.png',
  '/icons/apple-touch-icon.png',
  '/icons/screenshot-run.png',
  '/icons/screenshot-plan.png',
];

/**
 * Generated by `src/app/manifest.ts` rather than served from `public/`, so neither list
 * above covers it. `sw.ts` promises that a request which misses the precache is a bug, and
 * a browser re-reading the manifest offline would otherwise be exactly that.
 */
const GENERATED_ASSETS = ['/manifest.webmanifest'];

/**
 * Changes on every build, so a deploy actually replaces the cached HTML. The pages are a few
 * kB each, so re-downloading all of them on an update costs nothing worth optimising.
 */
const buildRevision = process.env.BUILD_REVISION ?? String(Date.now());

const withSerwist = withSerwistInit({
  swSrc: 'src/app/sw.ts',
  swDest: 'public/sw.js',
  // Serwist's webpack plugin does not run under the Turbopack dev server, and an
  // offline-first app is easier to develop without a cache in the way.
  disable: !isProd,
  // Nothing to reload for: the app never talks to the network.
  reloadOnOnline: false,
  // We register the worker ourselves in `<UpdateToast>`, because the registration and the
  // "do not update mid-session" policy are the same concern.
  register: false,
  scope: `${basePath}/`,
  // **No base path here.** The plugin joins this with `basePath` itself
  // (`path.posix.join(basePath, swUrl)`), so writing it out produces
  // `/pocket-session-planner/pocket-session-planner/sw.js` in the `window.serwist` it
  // injects. `scope` above is used verbatim, which is why that one does carry it — the
  // asymmetry is the plugin's, not ours.
  swUrl: '/sw.js',

  additionalPrecacheEntries: [...ROUTES, ...PUBLIC_ASSETS, ...GENERATED_ASSETS].map((path) => ({
    url: `${basePath}${path}`,
    revision: buildRevision,
  })),

  manifestTransforms: [
    (entries) => ({
      manifest: entries.map((entry) => ({
        ...entry,
        // The plugin walks `public/` with the platform path separator, so a Windows build
        // emits `icons\icon-192.png` — a URL that 404s on every server on earth. Normalise
        // before it reaches the manifest.
        url: entry.url.replace(/\\/g, '/'),
      })),
      warnings: [],
    }),
  ],
});

export default withSerwist({
  output: 'export',
  basePath,
  assetPrefix: basePath,
  // Static hosts resolve /plan/ -> /plan/index.html.
  trailingSlash: true,
  images: { unoptimized: true },
  reactStrictMode: true,
  poweredByHeader: false,
  env: { NEXT_PUBLIC_BASE_PATH: basePath },
});
